### ISSUE TITLE
failed to load manifest for dependency `rhyolite`

### ISSUE THREAD

**Issue by michidk** [dust-engine/dust#5]
Hey, 

this project looks exactly what I need, so I wanted to try it out. But I cannot compile the example:
```
PS C:\Users\michi\development\private\dust> cargo run
error: failed to load manifest for workspace member `C:\Users\michi\development\private\dust\crates\render`

Caused by:
  failed to load manifest for dependency `rhyolite`

Caused by:
  failed to read `C:\Users\michi\development\private\rhyolite\core\Cargo.toml`

Caused by:
  The system cannot find the path specified. (os error 3)
```

**Comment by michidk** [comment]
Nevermind, I found the dependency: https://github.com/dust-engine/rhyolite

However, it seems like it's not compatible with Windows:
```
2023-04-12T20:26:00.315123Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_INCOMPATIBLE_DRIVER', C:\Users\michi\development\private\rhyolite\bevy\src\lib.rs:116:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\castle.exe` (exit code: 101)
```

**Comment by bjorn3** [comment]
Based on the source it looks like it is Windows compatible, but needs at least Vulkan 1.3 + a couple of extensions. Maybe your graphics driver is missing Vulkan 1.3 support or one of those extensions.

**Comment by Neo-Zhixing** [comment]
Also, please note that dust is currently in pre-release and documentation is lacking. If you would like to get early access or work together on this, feel free to hit me up on Discord. `Neo#2250`

**Comment by Neo-Zhixing** [comment]
Closing, `rhyolite` has been directly integrated into the cargo workspace.
