### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by aka-deVOID** [dust-engine/dust#6]
hi, I want to start contributing to this project, how can I start do you have a discord server?

**Comment by leonskidev** [comment]
> "Also, please note that dust is currently in pre-release and documentation is lacking. If you would like to get early access or work together on this, feel free to hit me up on Discord. `Neo#2250`" - https://github.com/dust-engine/dust/issues/5#issuecomment-1526967389

**Comment by aka-deVOID** [comment]
thanks
